# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CrashlyticsANDRemoteConfig' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

	pod 'FirebaseCore'
	pod 'FirebaseFirestore'
	pod 'FirebaseRemoteConfig'
	pod 'FirebaseCrashlytics'

  # Pods for CrashlyticsANDRemoteConfig

end
